# Generated by Django 5.2.7 on 2025-12-15 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0005_cart_productcart'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер получателя')),
                ('comment', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментарий к заказу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления доставки')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('home', models.CharField(max_length=100, verbose_name='Дом/Корпус')),
                ('flat', models.CharField(blank=True, max_length=100, null=True, verbose_name='Квартира номер')),
                ('status', models.BooleanField(default=False, verbose_name='Статус доставки (получна или нет)')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loft.city', verbose_name='Город')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loft.customer', verbose_name='Покупатель')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loft.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Доставку',
                'verbose_name_plural': 'Доставки',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='loft.region', verbose_name='Регион'),
        ),
    ]
