# Generated by Django 5.2.7 on 2025-12-26 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loft', '0007_order_productorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('text', models.CharField(max_length=350, verbose_name='Запрос покупателя')),
                ('photo', models.FileField(blank=True, null=True, upload_to='customers/', verbose_name='Файл, Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Запрос покупателя',
                'verbose_name_plural': 'Запросы покупателей',
            },
        ),
        migrations.AlterField(
            model_name='productorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='loft.order', verbose_name='Заказ'),
        ),
    ]
